name: Check CHANGELOG.md

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for CHANGELOG.md
        uses: dangoslen/changelog-enforcer@v3
        with:
          missingUpdateErrorMessage: 'Please add a changelog entry in the CHANGELOG.md file.'

