name: Check Labels

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: "work in progress, do not merge"
          add_comment: true
          message: "This PR is being prevented from merging because it presents one of the blocking labels: {{ provided }}."
